### ISSUE TITLE
Potential collection cleanup bug?

### ISSUE THREAD

**Issue by latentflip** [HenrikJoreteg/human-view#11]
Haven't dug into it completely, but as far as I can tell we only register subviews on the initial collection render (https://github.com/HenrikJoreteg/human-view/blob/master/human-view.js#L215) any collection views added later won't be added to that list.

**Comment by HenrikJoreteg** [comment]
"views" in that line is an array that gets individual item views added and removed from it in the lines below that.

When the parent view is destroyed the whole subviews array is flattened and each view is removed.

**Comment by HenrikJoreteg** [comment]
I could be missing something else of course.

**Comment by latentflip** [comment]
Nope you’re right, I missed the fact that it was push not concat, and so modifications to that views array would be maintained as it’s passed in by reference.

-- 
Philip Roberts
Sent with Airmail

On November 26, 2013 at 3:59:47 PM, Henrik Joreteg (notifications@github.com) wrote:

I could be missing something else of course.
