### ISSUE TITLE
events collection binding does not target view.$el

### ISSUE THREAD

**Issue by CNovakCAA** [HenrikJoreteg/human-view#20]
Using the events collection to bind events to the view actually binds the events to any element in the DOM that matches the selector passed in.

Instead, the events should bind only to children of the view's $el.

**Comment by HenrikJoreteg** [comment]
Can you explain what you mean by "using the events collection to bind events" and describe the problem it caused?

**Comment by HenrikJoreteg** [comment]
Human-View simply uses backbone's delegate events method. 

See here: https://github.com/jashkenas/backbone/blob/master/backbone.js#L1114

It's always `this.$el.on(`

**Comment by CNovakCAA** [comment]
I can't reproduce my own error. Not sure at this point. Closing this issue until I can confirm this exists.
